apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-kustomize-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hiramekun/kubernetes-playground.git
    targetRevision: HEAD
    path: kustomize-config/environments/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true